import streamlit as st
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go
from datetime import datetime
from fpdf import FPDF
import tempfile

# --- PAGE CONFIGURATION ---
st.set_page_config(layout="wide", page_title="EquiReport | AI Analyst", page_icon="📑")

# --- CUSTOM CSS (On-Screen Display) ---
st.markdown("""
    <style>
        .stApp { background-color: #0E1117; color: #FAFAFA; font-family: 'Helvetica', sans-serif; }
        .report-container {
            background-color: #161B22;
            padding: 30px;
            border-radius: 10px;
            border: 1px solid #30363D;
            margin-bottom: 20px;
        }
        .rating-badge {
            padding: 5px 15px; border-radius: 5px; font-weight: bold; font-size: 1.2rem; display: inline-block;
        }
        .buy { background-color: #238636; color: white; }
        .sell { background-color: #DA3633; color: white; }
        .hold { background-color: #D29922; color: black; }
        h1, h2, h3 { color: #58A6FF; }
        .metric-label { font-size: 0.9rem; color: #8B949E; }
        .metric-value { font-size: 1.5rem; font-weight: bold; color: #C9D1D9; }
        hr { border: 0; border-top: 1px solid #30363D; }
    </style>
""", unsafe_allow_html=True)

# --- LOGIC ENGINE (THE "AI") ---
class ReportEngine:
    def __init__(self, df, info):
        self.df = df
        self.info = info
        self.close = df['Close'].iloc[-1]
        self.sma200 = df['Close'].rolling(200).mean().iloc[-1]
    
    def get_rating(self):
        score = 0
        if self.close > self.sma200: score += 1
        if self.info.get('forwardPE', 20) < 25: score += 1
        if self.info.get('profitMargins', 0) > 0.10: score += 1
        
        if score == 3: return "STRONG BUY", "buy"
        elif score == 2: return "BUY", "buy"
        elif score == 1: return "HOLD", "hold"
        else: return "SELL", "sell"

    def generate_thesis(self):
        reasons = []
        pe = self.info.get('trailingPE')
        if pe:
            if pe < 15: reasons.append(f"Undervalued: P/E is {pe:.2f}.")
            elif pe > 50: reasons.append(f"Premium Valuation: P/E is {pe:.2f}.")
            else: reasons.append(f"Fair Valuation: P/E is {pe:.2f}.")
        
        if self.close > self.sma200: reasons.append("Technical Uptrend: Trading above 200-day Moving Average.")
        else: reasons.append("Technical Downtrend: Trading below 200-day Moving Average.")
        
        margins = self.info.get('profitMargins', 0)
        reasons.append(f"Profitability: {margins*100:.1f}% net margins.")
        
        return "\n".join(reasons)

    def get_risks(self):
        risks = []
        if self.info.get('beta', 1.0) > 1.5: risks.append("High Volatility (Beta > 1.5)")
        if self.info.get('debtToEquity', 0) > 150: risks.append("High Leverage (Debt/Eq > 150)")
        if self.info.get('shortRatio', 0) > 5: risks.append("High Short Interest")
        if not risks: risks.append("No major automated risks detected.")
        return risks

# --- PDF GENERATOR CLASS ---
class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Equity Research Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 6, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 10)
        self.multi_cell(0, 5, body)
        self.ln()

def create_pdf(ticker, info, rating, thesis, risks, metrics):
    pdf = PDFReport()
    pdf.add_page()
    
    # Title Section
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, f"{info.get('longName', ticker)} ({ticker})", 0, 1, 'L')
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f"Recommendation: {rating}", 0, 1, 'L')
    pdf.cell(0, 10, f"Current Price: ${info.get('currentPrice', 'N/A')}", 0, 1, 'L')
    pdf.ln(5)
    
    # Thesis
    pdf.chapter_title("Investment Thesis")
    pdf.chapter_body(thesis)
    
    # Ratios
    pdf.chapter_title("Key Financial Ratios")
    ratio_text = ""
    for k, v in metrics.items():
        ratio_text += f"{k}: {v}\n"
    pdf.chapter_body(ratio_text)
    
    # Risks
    pdf.chapter_title("Key Risks")
    risk_text = "\n".join([f"- {r}" for r in risks])
    pdf.chapter_body(risk_text)
    
    # Disclaimer
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI algorithm for educational purposes only. Not financial advice.")
    
    return pdf.output(dest='S').encode('latin-1')

# --- MAIN APP ---
@st.cache_data
def load_data(symbol):
    try:
        ticker = yf.Ticker(symbol)
        df = ticker.history(period="2y")
        if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.get_level_values(0)
        return df, ticker.info
    except: return None, None

# Sidebar
with st.sidebar:
    st.header("EquiReport Engine")
    symbol = st.text_input("Enter Ticker (e.g. AAPL, RELIANCE.NS)", "AAPL").upper()
    if st.button("Generate Report"):
        st.cache_data.clear()

df, info = load_data(symbol)

if df is not None and not df.empty:
    engine = ReportEngine(df, info)
    rating_text, rating_class = engine.get_rating()
    thesis_text = engine.generate_thesis()
    risks_list = engine.get_risks()
    
    # Prepare Metrics for Display & PDF
    metrics_dict = {
        "P/E Ratio": f"{info.get('trailingPE', 'N/A')}",
        "Forward P/E": f"{info.get('forwardPE', 'N/A')}",
        "Market Cap": f"${info.get('marketCap',0)/1e9:.2f} B",
        "Beta": f"{info.get('beta', 'N/A')}"
    }

    # --- UI DISPLAY ---
    st.markdown(f"""
    <div class="report-container">
        <div style="display:flex; justify-content:space-between; align-items:center;">
            <div><h1 style="margin:0;">{info.get('longName', symbol)}</h1></div>
            <div><span class="rating-badge {rating_class}">{rating_text}</span></div>
        </div>
        <hr>
        <p><b>Investment Thesis:</b><br>{thesis_text.replace(chr(10), '<br>')}</p>
    </div>
    """, unsafe_allow_html=True)

    c1, c2 = st.columns([2, 1])
    with c1:
        # Chart
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=df.index, y=df['Close'], name='Price', line=dict(color='#58A6FF')))
        fig.add_trace(go.Scatter(x=df.index, y=df['Close'].rolling(200).mean(), name='200 DMA', line=dict(color='orange', dash='dash')))
        fig.update_layout(height=350, template="plotly_dark", margin=dict(l=0,r=0,t=0,b=0), paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        # Metrics & Risks
        st.markdown('<div class="report-container">', unsafe_allow_html=True)
        st.subheader("Key Data")
        for k, v in metrics_dict.items():
            st.write(f"**{k}:** {v}")
        st.markdown("---")
        st.subheader("Risks")
        for r in risks_list:
            st.write(f"⚠️ {r}")
        st.markdown('</div>', unsafe_allow_html=True)

    # --- PDF DOWNLOAD BUTTON ---
    # Create the PDF bytes
    pdf_bytes = create_pdf(symbol, info, rating_text, thesis_text, risks_list, metrics_dict)
    
    st.download_button(
        label="📄 Download PDF Report",
        data=pdf_bytes,
        file_name=f"{symbol}_Research_Report.pdf",
        mime="application/pdf",
        use_container_width=True
    )

else:
    st.error("Ticker not found. For Indian stocks, add .NS (e.g., RELIANCE.NS, TATASTEEL.NS). For US stocks use just the symbol (e.g., AAPL).")
